title: Jonathan McGechie # your name (or website title) here
logo: "/images/jonathan.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Man of Mystery
  <br><br>
  Data Engineer, Analyst, Life long learner
  <br><br>
  <a href="https://app.powerbi.com/groups/me/reports/dadec2ca-04b4-4f3a-9a6e-666739c096c9/ReportSection78e4e1f0d4b3662e1485?experience=power-bi&ownerId=8647d4d1-04d0-4c1a-8a4f-bf49d3e82ad6&referrer=embed.appsource"Power BI </a>
  <br><br>
 
  
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
#google_analytics: UA-000000-0 # your Google Analytics tracking ID here
